# Generated by Django 5.1.6 on 2025-04-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fat',
            field=models.IntegerField(default=0),
        ),
    ]
